### ISSUE TITLE
wyglad nie zgodny z projektem

### ISSUE THREAD

**Issue by jacekgalazka** [foxiu17/Nauka-HTML#4]
1)glowny div powinien byc wycentrowany w body
2)tlo powinno byc tylko jedno pod spodem i na nim powinien byc gradient

**Comment by foxiu17** [comment]
Tło poprawione, wcześniej nie zrozumiałem zamysłu.

**Comment by jacekgalazka** [comment]
pisz nazwy klas po angielsku w css , nauczysz sie szybciej języka
